apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-data-volume
spec:
  storageClassName: standard
  claimRef:
    name: airflow-data-pvc
    namespace: airflow
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: "/mnt"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - wiki-cluster-worker