apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-log-volume
spec:
  storageClassName: standard
  claimRef:
    name: airflow-log-pvc
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: "/log"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - wiki-cluster-worker
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-log-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi