FROM python:3.8-slim

# COPY requirements.txt /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt && rm -f /tmp/requirements.txt
RUN pip install urllib

RUN mkdir /opt/python
COPY src/ /opt/python/